
[env]
TERM = "xterm-256color"
import = "~/.config/alacritty/catppuccin-mocha.toml" 
[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "DroidSansM Nerd Font"
italic.family = "OperatorMono Nerd Font"
bold.family = "DroidSansM Nerd Font"
size = 18